-- Sprint 9.5 - Dados de teste IAWEB
-- Seed seguro para Supabase/PostgreSQL.
--
-- Regras aplicadas:
-- - Textos longos usam dollar-quoted strings.
-- - Campos JSONB usam jsonb_build_object/jsonb_build_array.
-- - Insert protegido por where not exists por email.

alter table public.diagnosticos
  add column if not exists cidade text not null default '';

with test_leads (
  empresa,
  nome_contacto,
  email,
  telefone,
  website,
  cidade,
  setor,
  objetivo,
  score_geral,
  score_website,
  score_google,
  score_conversao,
  score_automacao,
  score_crm,
  classificacao,
  status,
  origem,
  proxima_acao,
  notas,
  perda_mensal_estimada,
  plano_recomendado,
  score_projetado,
  melhoria_prevista,
  template_utilizado,
  whatsapp_status,
  whatsapp_message,
  email_subject,
  email_body,
  followup_3d,
  followup_7d,
  followup_15d,
  post_proposal_message,
  post_meeting_message,
  sales_agent_status,
  recomendacao_1,
  recomendacao_2,
  recomendacao_3,
  monthly_min,
  monthly_max,
  annual_min,
  annual_max,
  homepage_headline,
  objection_key_1,
  objection_value_1,
  objection_key_2,
  objection_value_2
) as (
  values
    ($$Alfa Remodelacoes$$,$$Miguel Santos$$,$$teste+alfa-remodelacoes@iaweb.pt$$,$$+351910000001$$,$$https://alfa-remodelacoes.pt$$,$$Porto$$,$$construcao$$,$$Receber pedidos de orcamento$$,28,22,24,34,14,18,$$Critico$$,$$novo$$,$$teste$$,$$Contactar e enviar simulacao$$,$$Lead ficticia Sprint 9.5 - cidade: Porto$$,24000,$$Sistema Comercial$$,82,54,$$construction$$,$$pendente$$,$$Ola Miguel, preparei uma simulacao visual para a Alfa Remodelacoes. Quer que lhe envie?$$,$$Analise digital da Alfa Remodelacoes$$,$$O score atual ficou em 28/100 e a simulacao projeta 82/100.$$,$$Miguel, posso mostrar-lhe a diferenca em 2 minutos?$$,$$A Alfa pode continuar a perder pedidos de orcamento qualificados. Quer ver a simulacao?$$,$$Podemos reabrir a conversa quando fizer sentido.$$,$$Miguel, enviei a proposta da Alfa Remodelacoes.$$,$$Obrigado pela reuniao. Deixo a simulacao alinhada com os proximos passos.$$,$$gerado$$,$$Reforcar prova de obra$$,$$Criar CTA de orcamento$$,$$Automatizar seguimento$$,12000,48000,144000,576000,$$Alfa Remodelacoes: obras com confianca e orcamentos claros.$$,$$ja_tenho_site$$,$$Claro. A questao e se o site atual gera pedidos qualificados.$$,$$esta_caro$$,$$Entendo. O ponto e comparar investimento com oportunidades perdidas.$$),
    ($$Clima Norte Obras$$,$$Rui Azevedo$$,$$teste+clima-norte-obras@iaweb.pt$$,$$+351910000002$$,$$https://climanorteobras.pt$$,$$Braga$$,$$construcao$$,$$Gerar mais leads qualificados$$,44,40,38,48,24,28,$$Em Desenvolvimento$$,$$contactado$$,$$teste$$,$$Enviar proposta curta$$,$$Lead ficticia Sprint 9.5 - cidade: Braga$$,18000,$$Sistema Comercial$$,86,42,$$construction$$,$$pendente$$,$$Ola Rui, a simulacao mostra uma melhoria de 44 para 86 pontos. Quer ver?$$,$$Simulacao IAWEB para Clima Norte Obras$$,$$Encontrei oportunidades de captacao e credibilidade.$$,$$Rui, deixo a simulacao pronta se quiser avaliar.$$,$$A oportunidade de pedidos qualificados continua aberta.$$,$$Posso enviar um resumo com score, homepage e plano.$$,$$Rui, proposta enviada com foco em captacao.$$,$$Obrigado pela reuniao, seguimos com o plano combinado?$$,$$gerado$$,$$Melhorar portfolio$$,$$Criar funil de pedidos$$,$$Reforcar Google$$,8000,36000,96000,432000,$$Clima Norte Obras: remodelacoes com processo claro.$$,$$nao_tenho_interesse_agora$$,$$Sem problema. Posso deixar a simulacao para ver depois.$$,$$depois_vejo$$,$$Combinado, envio um resumo curto.$$),
    ($$Clinica Sorriso Norte$$,$$Dra. Ines Matos$$,$$teste+clinica-sorriso-norte@iaweb.pt$$,$$+351910000003$$,$$https://clinicasorrisonorte.pt$$,$$Porto$$,$$clinicas$$,$$Aumentar marcacoes$$,34,28,30,44,18,22,$$Critico$$,$$novo$$,$$teste$$,$$Enviar simulacao de marcacoes$$,$$Lead ficticia Sprint 9.5 - cidade: Porto$$,15000,$$Website Profissional$$,87,53,$$clinic$$,$$pendente$$,$$Ola Ines, preparei uma simulacao para gerar mais marcacoes. Quer que lhe envie?$$,$$Score digital da Clinica Sorriso Norte$$,$$A homepage projetada aumenta confianca e marcacoes.$$,$$Ines, posso mostrar a diferenca em 2 minutos?$$,$$A clinica pode estar a perder marcacoes para concorrentes.$$,$$Quando fizer sentido, envio um resumo com a simulacao.$$,$$Ines, enviei a proposta para a clinica.$$,$$Obrigado pela reuniao. A prioridade ficou clara: marcacoes.$$,$$gerado$$,$$Aumentar marcacoes$$,$$Melhorar reputacao$$,$$Criar WhatsApp rapido$$,3000,57000,36000,684000,$$Clinica Sorriso Norte: mais marcacoes com confianca.$$,$$ja_tenho_site$$,$$Perfeito. A analise mostra se o site atual converte marcacoes.$$,$$nao_acredito$$,$$Nao prometemos resultados; mostramos clareza, prova e medicao.$$),
    ($$Dental Prime Coimbra$$,$$Joana Ferreira$$,$$teste+dental-prime-coimbra@iaweb.pt$$,$$+351910000004$$,$$https://dentalprimecoimbra.pt$$,$$Coimbra$$,$$clinicas$$,$$Aumentar marcacoes$$,62,66,54,68,34,42,$$Em Desenvolvimento$$,$$reuniao$$,$$teste$$,$$Validar proposta$$,$$Lead ficticia Sprint 9.5 - cidade: Coimbra$$,9000,$$Website Profissional$$,91,29,$$clinic$$,$$pendente$$,$$Ola Joana, a simulacao projeta 91/100 para a Dental Prime. Posso enviar?$$,$$Dental Prime Coimbra: oportunidade digital$$,$$A presenca atual tem base, mas pode converter mais.$$,$$Joana, deixo a simulacao para avaliarmos?$$,$$O potencial de marcacoes continua relevante.$$,$$Posso enviar o resumo da proposta quando quiser.$$,$$Joana, proposta enviada para validacao.$$,$$Obrigado pela reuniao. Ficou alinhado o foco em marcacoes.$$,$$gerado$$,$$Otimizar tratamentos$$,$$Melhorar Google$$,$$Criar follow-up$$,1500,27000,18000,324000,$$Dental Prime Coimbra: transformar pesquisa em marcacao.$$,$$esta_caro$$,$$Podemos comecar pelo pacote mais ajustado.$$,$$tenho_alguem$$,$$A simulacao pode servir como referencia para a equipa atual.$$),
    ($$Imob Vista Atlantico$$,$$Carla Nunes$$,$$teste+imob-vista-atlantico@iaweb.pt$$,$$+351910000005$$,$$https://imobvistaatlantico.pt$$,$$Lisboa$$,$$imobiliario$$,$$Gerar mais leads qualificados$$,48,46,42,54,28,36,$$Em Desenvolvimento$$,$$simulacao$$,$$teste$$,$$Enviar homepage gerada$$,$$Lead ficticia Sprint 9.5 - cidade: Lisboa$$,30000,$$IAWEB Growth Engine$$,88,40,$$realestate$$,$$pendente$$,$$Ola Carla, tenho uma simulacao para captar mais proprietarios. Quer ver?$$,$$Simulacao imobiliaria para Imob Vista Atlantico$$,$$O score projetado mostra melhoria forte em credibilidade.$$,$$Carla, posso mostrar a diferenca rapidamente?$$,$$Proprietarios podem continuar a escolher concorrentes.$$,$$Envio um resumo com a homepage e ROI?$$,$$Carla, proposta enviada com Growth Engine.$$,$$Obrigado pela reuniao, seguimos para proposta final?$$,$$gerado$$,$$Captar proprietarios$$,$$Valorizar imoveis$$,$$Automatizar seguimento$$,6000,64000,72000,768000,$$Imob Vista Atlantico: marca imobiliaria premium.$$,$$ja_tenho_site$$,$$A questao e se o site capta proprietarios e compradores.$$,$$depois_vejo$$,$$Envio um resumo para ver quando puder.$$),
    ($$CasaLusa Premium$$,$$Pedro Lima$$,$$teste+casalusa-premium@iaweb.pt$$,$$+351910000006$$,$$https://casalusapremium.pt$$,$$Cascais$$,$$imobiliario$$,$$Melhorar percecao de valor$$,78,82,74,76,54,62,$$Forte$$,$$proposta$$,$$teste$$,$$Follow-up proposta$$,$$Lead ficticia Sprint 9.5 - cidade: Cascais$$,12000,$$IAWEB Growth Engine$$,94,16,$$realestate$$,$$pendente$$,$$Ola Pedro, a CasaLusa ja tem boa base. A simulacao mostra como escalar captacao.$$,$$CasaLusa Premium: crescimento digital$$,$$A oportunidade esta em otimizar um sistema que ja tem base.$$,$$Pedro, quer rever a simulacao comigo?$$,$$A vantagem premium pode ser reforcada agora.$$,$$Posso enviar os proximos passos resumidos.$$,$$Pedro, proposta enviada com proximos passos.$$,$$Obrigado pela reuniao. Ficou claro o foco em crescimento.$$,$$gerado$$,$$Otimizar conversao$$,$$Reforcar autoridade$$,$$Criar relatorios$$,3000,24000,36000,288000,$$CasaLusa Premium: captar compradores e proprietarios.$$,$$esta_caro$$,$$Num caso premium, o foco e retorno e previsibilidade.$$,$$nao_acredito$$,$$Medimos contactos, pedidos e oportunidades reais.$$),
    ($$Bistro Avenida$$,$$Marta Costa$$,$$teste+bistro-avenida@iaweb.pt$$,$$+351910000007$$,$$https://bistroavenida.pt$$,$$Aveiro$$,$$restaurantes$$,$$Aumentar reservas$$,32,30,28,38,16,20,$$Critico$$,$$novo$$,$$teste$$,$$Enviar simulacao de reservas$$,$$Lead ficticia Sprint 9.5 - cidade: Aveiro$$,8000,$$Homepage Premium desde EUR 299$$,82,50,$$restaurant$$,$$pendente$$,$$Ola Marta, preparei uma simulacao para aumentar reservas no Bistro Avenida. Quer ver?$$,$$Bistro Avenida: reservas e presenca digital$$,$$O website pode simplificar reservas e pedidos.$$,$$Marta, mostro a diferenca em 2 minutos?$$,$$Reservas podem continuar a ir para concorrentes.$$,$$Posso enviar a simulacao para avaliar?$$,$$Marta, proposta enviada para homepage premium.$$,$$Obrigado pela reuniao. A prioridade e reservas.$$,$$gerado$$,$$Aumentar reservas$$,$$Mostrar menu$$,$$Facilitar contacto$$,1400,18000,16800,216000,$$Bistro Avenida: transformar visitas em reservas.$$,$$ja_tenho_site$$,$$Sim, mas queremos perceber se gera reservas.$$,$$esta_caro$$,$$Podemos comecar por uma homepage leve.$$),
    ($$Cantina do Mercado$$,$$Tiago Rocha$$,$$teste+cantina-mercado@iaweb.pt$$,$$+351910000008$$,$$https://cantinadomercado.pt$$,$$Viseu$$,$$restaurantes$$,$$Melhorar percecao de valor$$,56,60,48,58,32,40,$$Em Desenvolvimento$$,$$contactado$$,$$teste$$,$$Enviar resumo WhatsApp$$,$$Lead ficticia Sprint 9.5 - cidade: Viseu$$,5000,$$Homepage Premium desde EUR 299$$,86,30,$$restaurant$$,$$pendente$$,$$Ola Tiago, a simulacao mostra uma homepage focada em reservas. Quer receber?$$,$$Cantina do Mercado: mais reservas$$,$$A base existe, mas a conversao pode melhorar.$$,$$Tiago, envio a simulacao?$$,$$A procura local pode estar a perder-se.$$,$$Posso enviar um resumo curto.$$,$$Tiago, proposta enviada.$$,$$Obrigado pela reuniao, seguimos para conteudos?$$,$$gerado$$,$$Destacar menu$$,$$Melhorar localizacao$$,$$Criar reserva rapida$$,900,9000,10800,108000,$$Cantina do Mercado: menu, ambiente e reservas.$$,$$depois_vejo$$,$$Combinado, envio para ver quando puder.$$,$$tenho_alguem$$,$$A simulacao pode orientar quem trata disso.$$),
    ($$Lex Forte Advogados$$,$$Ana Ribeiro$$,$$teste+lex-forte@iaweb.pt$$,$$+351910000009$$,$$https://lexforte.pt$$,$$Lisboa$$,$$advocacia$$,$$Gerar mais leads qualificados$$,38,36,34,44,18,24,$$Critico$$,$$novo$$,$$teste$$,$$Contactar com abordagem consultiva$$,$$Lead ficticia Sprint 9.5 - cidade: Lisboa$$,20000,$$Sistema Comercial$$,84,46,$$lawyer$$,$$pendente$$,$$Ola Ana, preparei uma simulacao institucional para a Lex Forte. Quer que envie?$$,$$Lex Forte: analise digital$$,$$A presenca pode transmitir mais autoridade e gerar consultas.$$,$$Ana, posso mostrar a diferenca em 2 minutos?$$,$$Consultas qualificadas podem continuar invisiveis.$$,$$Envio um resumo quando fizer sentido.$$,$$Ana, proposta enviada com foco em autoridade.$$,$$Obrigado pela reuniao. Foco: consultas qualificadas.$$,$$gerado$$,$$Reforcar autoridade$$,$$Criar consulta inicial$$,$$Melhorar prova$$,1000,50000,12000,600000,$$Lex Forte: autoridade juridica clara.$$,$$nao_tenho_interesse_agora$$,$$Sem problema, deixo a simulacao como referencia.$$,$$nao_acredito$$,$$Validamos com consultas e contactos reais.$$),
    ($$Matos e Silva Legal$$,$$Sofia Matos$$,$$teste+matos-silva-legal@iaweb.pt$$,$$+351910000010$$,$$https://matossilvalegal.pt$$,$$Porto$$,$$advocacia$$,$$Melhorar website$$,69,72,62,70,42,52,$$Em Desenvolvimento$$,$$proposta$$,$$teste$$,$$Aguardar decisao$$,$$Lead ficticia Sprint 9.5 - cidade: Porto$$,10000,$$Sistema Comercial$$,92,23,$$lawyer$$,$$pendente$$,$$Ola Sofia, a simulacao melhora a comunicacao juridica e projeta 92/100. Quer rever?$$,$$Matos e Silva Legal: proposta digital$$,$$A base e boa, a oportunidade e converter melhor.$$,$$Sofia, posso reenviar a simulacao?$$,$$A oportunidade de consultas qualificadas continua ativa.$$,$$Podemos retomar quando fizer sentido.$$,$$Sofia, proposta enviada para avaliacao.$$,$$Obrigado pela reuniao. Ficam proximos passos alinhados.$$,$$gerado$$,$$Melhorar areas de pratica$$,$$Reforcar credibilidade$$,$$Criar contacto seguro$$,1000,22500,12000,270000,$$Matos e Silva Legal: clareza juridica e consulta.$$,$$esta_caro$$,$$Podemos fasear a implementacao.$$,$$ja_tenho_site$$,$$O foco e desempenho comercial, nao apenas site.$$),
    ($$Conta Clara$$,$$Nuno Teixeira$$,$$teste+conta-clara@iaweb.pt$$,$$+351910000011$$,$$https://contaclara.pt$$,$$Braga$$,$$contabilidade$$,$$Organizar funil comercial$$,46,44,40,52,30,44,$$Em Desenvolvimento$$,$$simulacao$$,$$teste$$,$$Enviar proposta de sistema$$,$$Lead ficticia Sprint 9.5 - cidade: Braga$$,6000,$$Sistema Comercial$$,86,40,$$accounting$$,$$pendente$$,$$Ola Nuno, preparei uma simulacao para captar clientes recorrentes. Quer ver?$$,$$Conta Clara: sistema comercial$$,$$A oportunidade e transformar procura em clientes recorrentes.$$,$$Nuno, posso mostrar a diferenca?$$,$$Clientes recorrentes podem estar a ser perdidos.$$,$$Envio resumo com score e plano?$$,$$Nuno, proposta enviada com sistema comercial.$$,$$Obrigado pela reuniao. Foco em clientes recorrentes.$$,$$gerado$$,$$Captar clientes recorrentes$$,$$Melhorar clareza$$,$$Criar CRM$$,900,12000,10800,144000,$$Conta Clara: contabilidade clara para decidir melhor.$$,$$tenho_alguem$$,$$A simulacao pode orientar a equipa atual.$$,$$esta_caro$$,$$Podemos comecar pelo sistema essencial.$$),
    ($$Fiscalis Pro$$,$$Helena Duarte$$,$$teste+fiscalis-pro@iaweb.pt$$,$$+351910000012$$,$$https://fiscalispro.pt$$,$$Coimbra$$,$$contabilidade$$,$$Gerar mais leads qualificados$$,84,88,80,82,62,70,$$Forte$$,$$negociacao$$,$$teste$$,$$Negociar scope mensal$$,$$Lead ficticia Sprint 9.5 - cidade: Coimbra$$,4000,$$IAWEB Growth Engine$$,96,12,$$accounting$$,$$pendente$$,$$Ola Helena, a Fiscalis Pro ja tem boa base. A simulacao mostra como escalar.$$,$$Fiscalis Pro: crescimento digital$$,$$A melhoria esta no sistema de captacao e follow-up.$$,$$Helena, quer rever o plano Growth?$$,$$Ha potencial para tornar a captacao mais previsivel.$$,$$Posso enviar resumo executivo.$$,$$Helena, proposta Growth enviada.$$,$$Obrigado pela reuniao. Seguimos para ajustes finais?$$,$$gerado$$,$$Escalar captacao$$,$$Automatizar relatorios$$,$$Melhorar follow-up$$,900,5400,10800,64800,$$Fiscalis Pro: contabilidade com decisao e crescimento.$$,$$esta_caro$$,$$Aqui falamos de escala, nao de presenca basica.$$,$$nao_acredito$$,$$Medimos leads, reunioes e clientes recorrentes.$$),
    ($$Obra Viva$$,$$Ricardo Gomes$$,$$teste+obra-viva@iaweb.pt$$,$$+351910000013$$,$$https://obraviva.pt$$,$$Setubal$$,$$construcao$$,$$Receber pedidos de orcamento$$,72,76,68,72,50,58,$$Forte$$,$$reuniao$$,$$teste$$,$$Preparar proposta final$$,$$Lead ficticia Sprint 9.5 - cidade: Setubal$$,14000,$$Sistema Comercial$$,93,21,$$construction$$,$$pendente$$,$$Ola Ricardo, a Obra Viva tem boa base. A simulacao projeta 93/100. Quer ver?$$,$$Obra Viva: orcamentos qualificados$$,$$A oportunidade e automatizar resposta e prova visual.$$,$$Ricardo, mostro a simulacao?$$,$$Pedidos qualificados podem continuar dispersos.$$,$$Posso enviar resumo com ROI.$$,$$Ricardo, proposta final enviada.$$,$$Obrigado pela reuniao. Foco em orcamentos.$$,$$gerado$$,$$Otimizar orcamentos$$,$$Automatizar resposta$$,$$Criar prova visual$$,8000,28800,96000,345600,$$Obra Viva: pedidos de orcamento com confianca.$$,$$ja_tenho_site$$,$$Sim, agora e otimizar para pedidos qualificados.$$,$$depois_vejo$$,$$Envio resumo para guardar.$$),
    ($$Smile Hub Lisboa$$,$$Mariana Lopes$$,$$teste+smile-hub-lisboa@iaweb.pt$$,$$+351910000014$$,$$https://smilehublisboa.pt$$,$$Lisboa$$,$$clinicas$$,$$Aumentar marcacoes$$,88,92,84,88,70,78,$$Forte$$,$$fechado$$,$$teste$$,$$Onboarding marcado$$,$$Lead ficticia Sprint 9.5 - cidade: Lisboa$$,7000,$$IAWEB Growth Engine$$,98,10,$$clinic$$,$$pendente$$,$$Ola Mariana, deixo o resumo da simulacao aprovada para a Smile Hub.$$,$$Smile Hub Lisboa: onboarding$$,$$A proposta esta alinhada com marcacoes e automacao.$$,$$Mariana, confirmamos os acessos?$$,$$Seguimos com onboarding e conteudos.$$,$$Deixo o resumo para a equipa.$$,$$Mariana, proposta aprovada e proximos passos enviados.$$,$$Obrigado pela reuniao. Seguimos para implementacao.$$,$$gerado$$,$$Escalar marcacoes$$,$$Automatizar follow-up$$,$$Reforcar prova social$$,1500,10800,18000,129600,$$Smile Hub Lisboa: marcacoes e confianca em escala.$$,$$tenho_alguem$$,$$Vamos colaborar com a equipa existente.$$,$$esta_caro$$,$$O foco e escala e previsibilidade.$$),
    ($$Prime Keys Imobiliaria$$,$$Andre Costa$$,$$teste+prime-keys@iaweb.pt$$,$$+351910000015$$,$$https://primekeys.pt$$,$$Porto$$,$$imobiliario$$,$$Gerar mais leads qualificados$$,24,20,22,30,12,18,$$Critico$$,$$perdido$$,$$teste$$,$$Nutrir no futuro$$,$$Lead ficticia Sprint 9.5 - cidade: Porto$$,30000,$$IAWEB Growth Engine$$,80,56,$$realestate$$,$$pendente$$,$$Ola Andre, deixo a simulacao da Prime Keys caso queira retomar.$$,$$Prime Keys: oportunidade digital$$,$$O score atual mostra uma oportunidade forte de reposicionamento.$$,$$Andre, quer que envie a simulacao?$$,$$A perda invisivel pode continuar relevante.$$,$$Quando fizer sentido, retomamos.$$,$$Andre, proposta arquivada para futura retoma.$$,$$Obrigado pela reuniao. Fico disponivel para retomar.$$,$$gerado$$,$$Criar marca premium$$,$$Captar proprietarios$$,$$Organizar leads$$,6000,64000,72000,768000,$$Prime Keys: captacao imobiliaria premium.$$,$$nao_tenho_interesse_agora$$,$$Sem problema, fica a referencia.$$,$$esta_caro$$,$$Podemos fasear a entrada.$$),
    ($$Mesa 21$$,$$Luis Martins$$,$$teste+mesa21@iaweb.pt$$,$$+351910000016$$,$$https://mesa21.pt$$,$$Lisboa$$,$$restaurantes$$,$$Aumentar reservas$$,91,94,88,90,74,80,$$Forte$$,$$fechado$$,$$teste$$,$$Preparar conteudos$$,$$Lead ficticia Sprint 9.5 - cidade: Lisboa$$,3000,$$Homepage Premium desde EUR 299$$,99,8,$$restaurant$$,$$pendente$$,$$Ola Luis, a homepage aprovada pode reforcar reservas e recorrencia.$$,$$Mesa 21: homepage aprovada$$,$$A base e excelente; agora otimizamos reservas.$$,$$Luis, confirmamos conteudos?$$,$$Seguimos com detalhes de menu e fotos.$$,$$Envio resumo da implementacao.$$,$$Luis, proposta aprovada.$$,$$Obrigado pela reuniao. Seguimos com homepage.$$,$$gerado$$,$$Otimizar reservas$$,$$Criar campanhas$$,$$Reforcar recorrencia$$,900,6300,10800,75600,$$Mesa 21: reservas e experiencia premium.$$,$$ja_tenho_site$$,$$Agora e melhorar conversao e reservas.$$,$$tenho_alguem$$,$$Podemos alinhar com a equipa interna.$$),
    ($$Ordem Legal Norte$$,$$Vasco Pereira$$,$$teste+ordem-legal-norte@iaweb.pt$$,$$+351910000017$$,$$https://ordemlegalnorte.pt$$,$$Braga$$,$$advocacia$$,$$Melhorar percecao de valor$$,52,54,46,56,34,42,$$Em Desenvolvimento$$,$$contactado$$,$$teste$$,$$Enviar email inicial$$,$$Lead ficticia Sprint 9.5 - cidade: Braga$$,8000,$$Sistema Comercial$$,88,36,$$lawyer$$,$$pendente$$,$$Ola Vasco, preparei uma simulacao para reforcar autoridade. Quer receber?$$,$$Ordem Legal Norte: analise digital$$,$$A presenca pode converter melhor consultas qualificadas.$$,$$Vasco, posso mostrar a diferenca?$$,$$Consultas podem continuar a escapar.$$,$$Envio um resumo com a simulacao?$$,$$Vasco, proposta enviada.$$,$$Obrigado pela reuniao. Foco em consultas.$$,$$gerado$$,$$Clarificar areas$$,$$Reforcar autoridade$$,$$Gerar consultas$$,1000,22500,12000,270000,$$Ordem Legal Norte: autoridade e consulta.$$,$$ja_tenho_site$$,$$A questao e performance comercial.$$,$$nao_acredito$$,$$Validamos com contactos reais.$$),
    ($$Numeris Contabilidade$$,$$Patricia Alves$$,$$teste+numeris@iaweb.pt$$,$$+351910000018$$,$$https://numeris.pt$$,$$Faro$$,$$contabilidade$$,$$Organizar funil comercial$$,30,28,26,36,16,24,$$Critico$$,$$novo$$,$$teste$$,$$Contactar por WhatsApp$$,$$Lead ficticia Sprint 9.5 - cidade: Faro$$,9000,$$Sistema Comercial$$,82,52,$$accounting$$,$$pendente$$,$$Ola Patricia, encontrei uma oportunidade clara para a Numeris. Quer ver a simulacao?$$,$$Numeris: funil comercial$$,$$A empresa pode captar clientes recorrentes com mais previsibilidade.$$,$$Patricia, mostro em 2 minutos?$$,$$Clientes recorrentes podem continuar invisiveis.$$,$$Envio um resumo curto?$$,$$Patricia, proposta preparada.$$,$$Obrigado pela reuniao. Foco em funil.$$,$$gerado$$,$$Criar funil$$,$$Captar clientes recorrentes$$,$$Automatizar resposta$$,300,12000,3600,144000,$$Numeris: contabilidade com clareza e crescimento.$$,$$depois_vejo$$,$$Envio resumo para avaliar depois.$$,$$esta_caro$$,$$Podemos comecar pelo essencial.$$),
    ($$Studio Obra Design$$,$$Beatriz Melo$$,$$teste+studio-obra-design@iaweb.pt$$,$$+351910000019$$,$$https://studioobradesign.pt$$,$$Aveiro$$,$$construcao$$,$$Melhorar percecao de valor$$,66,70,60,68,42,50,$$Em Desenvolvimento$$,$$proposta$$,$$teste$$,$$Rever escopo$$,$$Lead ficticia Sprint 9.5 - cidade: Aveiro$$,16000,$$Website Profissional$$,91,25,$$construction$$,$$pendente$$,$$Ola Beatriz, a simulacao valoriza o portfolio e gera pedidos qualificados. Quer rever?$$,$$Studio Obra Design: proposta visual$$,$$A oportunidade e converter percecao premium em pedidos.$$,$$Beatriz, posso reenviar a simulacao?$$,$$Pedidos qualificados podem continuar abaixo do potencial.$$,$$Envio resumo com homepage e ROI.$$,$$Beatriz, proposta enviada.$$,$$Obrigado pela reuniao. Foco em portfolio e pedidos.$$,$$gerado$$,$$Valorizar portfolio$$,$$Criar pedido qualificado$$,$$Melhorar mobile$$,8000,28800,96000,345600,$$Studio Obra Design: portfolio que gera pedidos.$$,$$ja_tenho_site$$,$$Aqui o foco e reposicionamento e conversao.$$,$$tenho_alguem$$,$$A simulacao pode orientar a equipa.$$),
    ($$Clinica Vitalis$$,$$Teresa Gomes$$,$$teste+clinica-vitalis@iaweb.pt$$,$$+351910000020$$,$$https://clinicavitalis.pt$$,$$Funchal$$,$$clinicas$$,$$Aumentar marcacoes$$,74,78,70,76,52,58,$$Forte$$,$$negociacao$$,$$teste$$,$$Negociar mensalidade$$,$$Lead ficticia Sprint 9.5 - cidade: Funchal$$,8000,$$Website Profissional$$,94,20,$$clinic$$,$$pendente$$,$$Ola Teresa, a Vitalis pode subir para 94/100 com foco em marcacoes. Quer rever?$$,$$Clinica Vitalis: score projetado$$,$$A base e boa; ha oportunidade em automacao e prova social.$$,$$Teresa, posso enviar resumo?$$,$$Marcacoes podem continuar abaixo do potencial.$$,$$Retomamos quando fizer sentido.$$,$$Teresa, proposta enviada com ajustes.$$,$$Obrigado pela reuniao. Foco em marcacoes e follow-up.$$,$$gerado$$,$$Otimizar marcacoes$$,$$Melhorar prova social$$,$$Automatizar follow-up$$,1500,13500,18000,162000,$$Clinica Vitalis: marcacoes com confianca.$$,$$esta_caro$$,$$Podemos ajustar escopo inicial.$$,$$nao_acredito$$,$$Medimos marcacoes e pedidos reais.$$)
)
insert into public.diagnosticos (
  empresa,
  nome_contacto,
  email,
  telefone,
  website,
  cidade,
  setor,
  objetivo,
  score_geral,
  score_website,
  score_google,
  score_conversao,
  score_automacao,
  score_crm,
  classificacao,
  potencial_estimado,
  recomendacoes,
  status,
  origem,
  proxima_acao,
  notas,
  perda_mensal_estimada,
  impacto_financeiro,
  plano_recomendado,
  homepage_gerada,
  score_projetado,
  melhoria_prevista,
  template_utilizado,
  whatsapp_status,
  whatsapp_message,
  email_subject,
  email_body,
  followup_3d,
  followup_7d,
  followup_15d,
  objection_responses,
  post_proposal_message,
  post_meeting_message,
  sales_agent_status,
  created_at,
  updated_at
)
select
  empresa,
  nome_contacto,
  email,
  telefone,
  website,
  cidade,
  setor,
  objetivo,
  score_geral,
  score_website,
  score_google,
  score_conversao,
  score_automacao,
  score_crm,
  classificacao,
  $$Perda mensal estimada: EUR $$ || perda_mensal_estimada::text,
  jsonb_build_array(recomendacao_1, recomendacao_2, recomendacao_3),
  status,
  origem,
  proxima_acao,
  notas,
  perda_mensal_estimada,
  jsonb_build_object(
    'lostRevenueMonthly', jsonb_build_object('min', monthly_min, 'max', monthly_max),
    'lostRevenueAnnual', jsonb_build_object('min', annual_min, 'max', annual_max)
  ),
  plano_recomendado,
  jsonb_build_object(
    'templateId', template_utilizado,
    'copy', jsonb_build_object('headline', homepage_headline)
  ),
  score_projetado,
  melhoria_prevista,
  template_utilizado,
  whatsapp_status,
  whatsapp_message,
  email_subject,
  email_body,
  followup_3d,
  followup_7d,
  followup_15d,
  jsonb_build_object(
    objection_key_1, objection_value_1,
    objection_key_2, objection_value_2
  ),
  post_proposal_message,
  post_meeting_message,
  sales_agent_status,
  now(),
  now()
from test_leads
where not exists (
  select 1
  from public.diagnosticos existing
  where existing.email = test_leads.email
);
