import type { ConstructionDetectedDocument, ConstructionHealthCheckResult, ConstructionProject } from "./types"

export const constructionDemoProject: ConstructionProject = {
  id: "demo",
  organization_id: null,
  name: "Hotel Atlântico - Licenciamento e Execução",
  project_type: "hotel",
  country: "Portugal",
  city: "Lisboa",
  estimated_area_m2: 4200,
  client_type: "promotor_imobiliario",
  status: "demo",
  maturity_score: 78,
  risk_score: 36,
  complexity_score: 74,
  confidence_score: 81,
  analyses_count: 12,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
}

export const constructionDemoDocuments: ConstructionDetectedDocument[] = [
  {
    id: "demo-doc-arq",
    project_id: "demo",
    file_id: "demo-file-arq",
    document_type: "arquitetura",
    country: "Portugal",
    specialty: "arquitetura",
    confidence_score: 92,
    notes: "Classificacao demo por keywords de arquitetura.",
    ai_analysis_status: "success",
    ai_summary: "Projeto de arquitetura com plantas, cortes e informacao base suficiente para primeira leitura executiva.",
    detected_entities: { construction_elements: ["plantas", "cortes", "alçados"], documentary_risks: [] },
    title: "ARQ_Hotel_Atlantico_Plantas_Cortes.pdf",
    version: null,
    detected_confidence: 92,
    page_count: null,
    extracted_data: {},
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-doc-est",
    project_id: "demo",
    file_id: "demo-file-est",
    document_type: "estruturas",
    country: "Portugal",
    specialty: "estruturas",
    confidence_score: 88,
    notes: "Classificacao demo por keywords de estruturas.",
    ai_analysis_status: "success",
    ai_summary: "Documentacao estrutural com fundacoes e estrutura principal identificadas.",
    detected_entities: { construction_elements: ["fundacoes", "estrutura principal"], documentary_risks: [] },
    title: "EST_Estruturas_Fundacoes.pdf",
    version: null,
    detected_confidence: 88,
    page_count: null,
    extracted_data: {},
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-doc-mq",
    project_id: "demo",
    file_id: "demo-file-mq",
    document_type: "mapa de quantidades",
    country: "Portugal",
    specialty: "medicoes",
    confidence_score: 86,
    notes: "Classificacao demo por mapa de quantidades.",
    ai_analysis_status: "success",
    ai_summary: "Mapa de quantidades pronto para suportar estimativa preliminar.",
    detected_entities: { construction_elements: ["quantidades", "capitulos de obra"], documentary_risks: [] },
    title: "MQ_Hotel_Atlantico.xlsx",
    version: null,
    detected_confidence: 86,
    page_count: null,
    extracted_data: {},
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-doc-avac",
    project_id: "demo",
    file_id: "demo-file-avac",
    document_type: "AVAC",
    country: "Portugal",
    specialty: "avac",
    confidence_score: 83,
    notes: "Classificacao demo por especialidade AVAC.",
    ai_analysis_status: "success",
    ai_summary: "Especialidade AVAC identificada com potenciais implicacoes em custo e prazo.",
    detected_entities: { construction_elements: ["ventilacao", "climatizacao"], documentary_risks: ["compatibilizacao com arquitetura"] },
    title: "AVAC_Projeto_Base.pdf",
    version: null,
    detected_confidence: 83,
    page_count: null,
    extracted_data: {},
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-doc-ele",
    project_id: "demo",
    file_id: "demo-file-ele",
    document_type: "eletricidade",
    country: "Portugal",
    specialty: "eletricidade",
    confidence_score: 81,
    notes: "Classificacao demo por especialidade eletrica.",
    ai_analysis_status: "success",
    ai_summary: "Especialidade eletrica identificada com quadros e iluminacao.",
    detected_entities: { construction_elements: ["quadros eletricos", "iluminacao"], documentary_risks: [] },
    title: "ELE_Quadros_Iluminacao.pdf",
    version: null,
    detected_confidence: 81,
    page_count: null,
    extracted_data: {},
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-doc-scie",
    project_id: "demo",
    file_id: "demo-file-scie",
    document_type: "SCIE",
    country: "Portugal",
    specialty: "scie",
    confidence_score: 84,
    notes: "Classificacao demo por seguranca contra incendio.",
    ai_analysis_status: "success",
    ai_summary: "Documento SCIE identificado, importante para licenciamento e seguranca.",
    detected_entities: { construction_elements: ["medidas de autoprotecao", "seguranca contra incendio"], documentary_risks: ["validacao regulamentar"] },
    title: "SCIE_Medidas_Autoprotecao.pdf",
    version: null,
    detected_confidence: 84,
    page_count: null,
    extracted_data: {},
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-doc-ce",
    project_id: "demo",
    file_id: "demo-file-ce",
    document_type: "caderno de encargos",
    country: "Portugal",
    specialty: "caderno de encargos",
    confidence_score: 61,
    notes: "Classificacao demo com baixa confianca por documento parcial.",
    ai_analysis_status: "fallback",
    ai_summary: null,
    detected_entities: { construction_elements: ["condicoes tecnicas"], documentary_risks: ["versao preliminar"] },
    title: "CE_Condicoes_Tecnicas_Preliminar.docx",
    version: null,
    detected_confidence: 61,
    page_count: null,
    extracted_data: {},
    created_at: new Date().toISOString(),
  },
]

export const constructionDemoHealthCheck: ConstructionHealthCheckResult = {
  maturityScore: 78,
  riskScore: 36,
  complexityScore: 74,
  confidenceScore: 81,
  documentsFound: 12,
  identifiedSpecialties: ["arquitetura", "estruturas", "medicoes", "avac", "eletricidade", "scie"],
  missingCriticalDocuments: ["caderno de encargos final"],
  alerts: [
    {
      type: "missing_document",
      title: "Documento critico em falta: caderno de encargos final",
      severity: "high",
      recommendation: "Adicionar versao final do caderno de encargos antes de fechar estimativa comercial ou proposta.",
    },
    {
      type: "scope_alignment",
      title: "Complexidade elevada para fase documental atual",
      severity: "medium",
      recommendation: "Validar compatibilizacao entre arquitetura, estruturas e AVAC antes da proxima fase.",
    },
  ],
  costEstimate: {
    estimatedCostMin: 9700000,
    estimatedCostMid: 15100000,
    estimatedCostMax: 20500000,
    costConfidence: 77,
    costNotes: [
      "Estimativa preliminar inteligente, nao substitui orçamento final.",
      "Risco moderado e complexidade elevada aumentaram a faixa superior.",
    ],
  },
  scheduleEstimate: {
    estimatedMonthsMin: 18,
    estimatedMonthsMid: 26,
    estimatedMonthsMax: 34,
    scheduleConfidence: 75,
    scheduleNotes: [
      "Estimativa preliminar inteligente, nao substitui planeamento contratual.",
      "Complexidade e area elevada aumentaram a duracao provavel.",
    ],
  },
  estimates: [],
  scores: [],
  risks: [],
  knowledgeGraph: {
    mainEntities: ["hotel", "arquitetura", "estruturas", "mapa de quantidades", "SCIE", "AVAC"],
    mainRelations: [
      "mapa de quantidades equivalent to DQE",
      "mapa de quantidades equivalent to Mediciones",
      "SCIE requires regra de conformidade SCIE",
      "caderno de encargos improves maturity documentacao acima da media",
    ],
    derivedRisks: ["Documento critico em falta: caderno de encargos final"],
    costFactors: ["AVAC e SCIE podem influenciar custo tecnico do hotel."],
    scheduleFactors: ["Compatibilizacao de especialidades pode influenciar prazo."],
    recommendations: [
      "Fechar caderno de encargos final antes da proposta.",
      "Validar SCIE com requisitos de licenciamento.",
      "Cruzar mapa de quantidades com especialidades tecnicas.",
    ],
  },
}
